# https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/elastic-beanstalk/command/UpdateEnvironmentCommand/
name: 'Elastic Beanstalk Deploy Action'
description: 'Deploy to Elastic Beanstalk'
author: '7empestx'
inputs:
  # aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  aws_access_key:
    description: 'AWS Access Key Id'
    required: true

  # aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  aws_secret_key:
    description: 'AWS Secret Key'
    required: true

  #region: us-west-2
  aws_region:
    description: 'Region'
    required: true
    default: 'us-west-2'

  # application_name: MyApplicationName
  application_name:
    description: 'Application Name'
    required: true
    default: 'MyApplicationName'

  # environment_name: MyApplication-Environment
  environment_name:
    description: 'Environment Name'
    required: true
    default: 'MyApplication-Environment'

  # version_label: 12345
  version_label:
    description: 'Version Label'
    required: false
    default: '12345'

  # We should not need to package the application in the action
  # deployment_package: deploy.zip
  # deployment_package: deploy.zip
  platform:
    description: 'Platform'
    required: true
    default: 'golang'

outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node20'
  main: 'index.js'
